### ISSUE TITLE
求问怎么配合 neovide 使用啊

### ISSUE THREAD

**Issue by Liloupar** [daog1/lvim#1]

**Comment by daog1** [comment]
我在mac上不需要配置，安装上，直接就可以使用，我记得在windows上，你找到lvim到启动lvim.ps ，改下脚本把neovide 加到lvim.ps 里面就可以使用。

**Comment by Liloupar** [comment]
> 我在mac上不需要配置，安装上，直接就可以使用，我记得在windows上，你找到lvim到启动lvim.ps ，改下脚本把neovide 加到lvim.ps 里面就可以使用。

我也是在mac上, 但是启动后是neovim而不是lunarvim...

**Comment by daog1** [comment]
打开  ~/.local/bin/lvim 这样修改：
```
#exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
exec -a "$NVIM_APPNAME" neovide -- -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
```

**Comment by Liloupar** [comment]
> 打开 ~/.local/bin/lvim 这样修改：
> 
> ```
> #exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
> exec -a "$NVIM_APPNAME" neovide -- -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
> ```

可以了, 感谢
